### PR TITLE
Added support for netcoreapp3.1

### PR DESCRIPTION
**Pull request by johnsimons**
We have been using this lib for a while now, and now we are moving our WPF project to netcore3.1.
Unfortunately, this lib does not support netcore 😢 

So this is where this PR comes in.
I had to do a bit of work to the csproj files, in essence, upgrade them to the new csproj format.
Also as part of that change, I modified the targets, which means I had to drop v2.0 and v3.5 frameworks!
The good news is that with this change, this package can now be used in a netcoreapp3.1 project 🤗 

Also, because nuget packaging is now part of the project system, I configured the project to produce the nuget as part of the build, not sure if this is something you want or not?

Let me know how I can help to get this merged and released?

### CODE REVIEW

**Comment by dahall** [comment]
You can support .NET 2 and 3.5 in the new project format. Add `net2` and `net35` to the list in the `<TargetFrameworks>` tag.

**Comment by ricardopolo** [comment]
@johnsimons thanks for this PR!! we are happy to merge it!

For now I cannot merge it because the build is not working, right now it is not compiling:
https://ci.appveyor.com/project/tulpep/active-directory-object-picker/builds/30300328

Please also be sure it works with the old .NET and NetCore.

After this I will merge and release a new Nuget version.

Again, thank so much!

**Comment by dahall** [comment]
And, I have a great need for this project to still support .NET 2 and 3.5.

**Comment by ricardopolo** [comment]
@dahall do you think @johnsimons can release a version that works in .NET  2, 3.5 and also netcore or we should release a differente nuget/project?

**Comment by johnsimons** [comment]
I've just pushed a change to include `net20` and `net35`, 🤞

**Comment by johnsimons** [comment]
I'll look at the build failures now, sorry it may take me a while, not familiar with appveyor!

**Comment by johnsimons** [comment]
@dahall @ricardopolo I am trying to get the build in appveyor to work but struggling, help!

**Comment by johnsimons** [comment]
So I got a bit further, it seems I need to use the build script option, but it is still failing for net2 and net35, it is a bit weird because according to https://www.appveyor.com/docs/windows-images-software/#net-framework the `Visual Studio 2019` image should include all those frameworks

**Comment by ricardopolo** [comment]
Maybe @FeodorFitsner from Appveyor could help. Would you mind emailing support@appveyor.com to Feodor so he can help us reviewing this?

We are a paying customer of Appveyor so I think we have support for this! Thank you 😄

**Comment by johnsimons** [comment]
I may have found the problem https://stackoverflow.com/a/47190634

**Comment by johnsimons** [comment]
@dahall according to https://stackoverflow.com/a/47190634 it seems to build `net20` and `net35` with the new `dotnet` is not possible, we can still build with `msbuild`, but that will make building and developing against this lib a bit difficult.

So I was wondering, you say "I have a great need for this project to still support .NET 2 and 3.5", but given this lib has been stable for over a year (no code changes), could we remove these framework targets so we can get the netcore builds working and for users that still need the net20/35 point them to the old nuget package? Is this an option?

**Comment by dahall** [comment]
@johnsimons I have a project with about 3M downloads ([TaskScheduler](https://github.com/dahall/taskscheduler)) that uses this library and supports all the desktop .NET Framework versions. I have been asked to add .NET Core 3.1 support to it and am within a few days of completing my lib's changes, I need this library to also support those same versions. Moving this project to the SDK format was next on my list.

I can understand that not having an automated build process takes time when preparing a NuGet release, but other than that, I cannot see how it impacts much else. If msbuild still works, then why not just use it when building the library for release to NuGet?

**Comment by ricardopolo** [comment]
@johnsimons what about having two build scripts in appveyor?  Running `cmd: dotnet build -c Release` and later running `msbuild` command?

After that, having the two builds sucessfull, modify the nuget specs https://github.com/Tulpep/Active-Directory-Object-Picker/blob/master/Nuget/specs.nuspec with path of each resultant build.

Would you mind trying this please? If not I will try to do it on weekend

**Comment by johnsimons** [comment]
@ricardopolo @dahall 
I've spent a bit of time trying to solve the build for net20/35
So here are my finds. 
We can build net40+ using either msbuild16 or dotnet with the new project system.
To build net20/35 we need to use msbuild13 (I think this is the one shipped with VS2013), but and this is the problem, **we need the old project format**!

I guess we could have both project types + 2 different solutions? Do you want me to try that option?

**Comment by dahall** [comment]
I don't know which msbuild it uses, but I am using the new SDK project file format on my projects and building solutions with Visual Studio 2019 that have target frameworks from every type of .Net including 2.0 and 3.5.

**Comment by dahall** [comment]
See https://github.com/dahall/TaskScheduler/blob/master/TaskService/TaskService.csproj

**Comment by johnsimons** [comment]
@dahall I would appreciate some help with this, I think it comes down to appveyor but at this stage, I am out of ideas

**Comment by dahall** [comment]
@johnsimons I won't have time to look at this until tomorrow. Until then, check out [this link](https://github.com/dahall/Vanara/blob/master/WIndows.Forms/Vanara.Windows.Forms.csproj) to a project file that works well with WinForms controls targeting all kinds of .NET versions. The `<TargetFrameworks>` and `<UseWinForms>` tags are of particular mention.

**Comment by dahall** [comment]
Here's my changes and recommendations for the main project file. All changes have XML comments to explain them. I would suggest removing these before pushing. This builds with MSBUILD 16.0 from my command line without error.
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>ActiveDirectoryObjectPicker</AssemblyName>
    <AssemblyOriginatorKeyFile>Tulpep.ActiveDirectoryObjectPicker.snk</AssemblyOriginatorKeyFile>
    <UseWindowsForms>true</UseWindowsForms>
    <SignAssembly>true</SignAssembly>
    <PackageId>Tulpep.ActiveDirectoryObjectPicker</PackageId>
    <PackageVersion>2.0.7326</PackageVersion>
    <Title>Active Directory Object Picker</Title>
    <Authors>Armand du Plessis; Tulpep</Authors>
    <Description>Active Directory Object Picker.</Description>
    <PackageProjectUrl>https://github.com/Tulpep/Active-Directory-Dialogs</PackageProjectUrl>
    <PackageLicenseUrl>https://raw.githubusercontent.com/Tulpep/Active-Directory-Dialogs/master/LICENSE</PackageLicenseUrl>
    <IncludeSource>true</IncludeSource>
    <Company>Tulpep</Company>
    <DebugType>embedded</DebugType>

    <!-- Guidance is to separate with semicolons. -->
    <PackageTags>WPF;Active Directory;Dialog;WinForms;Windows Forms;Picker</PackageTags>
    <!-- I'd recommend using a variable reference so that only the AssemblyName value has to be changed. -->
    <AssemblyTitle>$(AssemblyName)</AssemblyTitle>
    <!-- Added .NET 2 and 3.5 and .NET Core 3.0. -->
    <TargetFrameworks>net20;net35;net40;net45;net452;net462;net472;net48;netcoreapp3.0;netcoreapp3.1</TargetFrameworks>
    <!-- The following line ensures that a blank product is not added since no Product tag is present. -->
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <!-- The following lines were in the orginal project files but didn't make it into this one. -->
    <RootNamespace>Tulpep.ActiveDirectoryObjectPicker</RootNamespace>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <!-- The following line replaces the AssemblyVersion and FileVersion tags. -->
    <VersionPrefix>2.0.7326</VersionPrefix>
    <!-- The following line removes the need to run a NuGet pack separately from Build.ps1. -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <!-- While making changes, it may be valuable to include the source and support symbol packages. -->
    <IncludeSource>true</IncludeSource>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  
  <!-- This following ItemGroup must be included if 'snupkg' is enabled above as the SymbolPackageFormat. -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
  </ItemGroup>
  <!-- This following ItemGroup must be included for all .NET Framework references. -->
  <ItemGroup Condition=" $(TargetFramework.StartsWith('net2')) Or $(TargetFramework.StartsWith('net3')) Or $(TargetFramework.StartsWith('net4')) ">
    <Reference Include="System" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Tulpep.ActiveDirectoryObjectPicker.snk" />
  </ItemGroup>
</Project>
```

**Comment by dahall** [comment]
If those changes work, please let me know after you commit them, but before publishing, as I would like to make some changes to XML comments in a few of the source files to eliminate some compiler warnings. I'll fix them and PR the results.

**Comment by dahall** [comment]
Looking at `appveyor.yaml`, you cannot use the `dotnet` compiler and get the results you want. You have to use `msbuild`. In the current file, the `msbuild` referenced is not v16 and will not work. You can remove the call to the nuget build script too if you have `msbuild` do it by including the `<GeneratePackageOnBuild>` tag in the .csproj file. You will also need to add `version_prefix: '{version}'` to the `dotnet_csproj` section if you accept my changes to the .csproj file. I would the completely remove the `build_script` section to see if it works by default with the VS2019 image.

**Comment by johnsimons** [comment]
@dahall, I can only do these changes on Tuesday. If you want, just fork my changes and push your changes based on my PR to see if they work on appveyor

**Comment by johnsimons** [comment]
Actually I have just given you guys rights to my branch, feel free to push to it.

**Comment by dahall** [comment]
I couldn't get @johnsimons repository to give me access, so I just pulled in his changes, my corrections and some warning fixes and put them in my own PR #35.

**Comment by johnsimons** [comment]
@dahall you probably received an email from GitHub to accept permission to my repo

**Comment by ricardopolo** [comment]
Fixed by #35

**Pull request closed without merging**
